fixed action: deploy_lambda_layer.yml

diff --git a/.github/workflows/deploy_lambda_layer.yml b/.github/workflows/deploy_lambda_layer.yml
--- a/.github/workflows/deploy_lambda_layer.yml
+++ b/.github/workflows/deploy_lambda_layer.yml
@@ -52,9 +52,18 @@ jobs:
 
       - name: Update Lambda function to use new Layer version
         run: |
-          aws lambda update-function-configuration \
-            --function-name cv-processor \
-            --layers $LAYER_ARN
+          MAX_RETRIES=5
+          COUNT=0
+          until aws lambda update-function-configuration --function-name cv-processor --layers $LAYER_ARN || [ $COUNT -eq $MAX_RETRIES ]; do
+            echo "Retrying in 10 seconds..."
+            sleep 10
+            COUNT=$((COUNT + 1))
+          done
+          
+          if [ $COUNT -eq $MAX_RETRIES ]; then
+            echo "Failed to update Lambda after $MAX_RETRIES attempts."
+            exit 1
+          fi
 
       - name: Cleanup generated files
         run: |
