actualizo workflow

diff --git a/.github/workflows/deploy_set_candidate_rating.yml b/.github/workflows/deploy_set_candidate_rating.yml
--- a/.github/workflows/deploy_set_candidate_rating.yml
+++ b/.github/workflows/deploy_set_candidate_rating.yml
@@ -1,4 +1,4 @@
-name: Deploy to AWS Lambda - set-candidate-rating
+name: Deploy to AWS Lambda - set-candidate-rating_handler
 
 on:
   push:
@@ -27,29 +27,29 @@ jobs:
       - name: Install dependencies and package Lambda for set-candidate-rating_handler
         run: |
           cd lambda/candidate_rating/set_candidate_rating
-          pip install -r requirements.txt -t python  
-          cp set_candidate_rating_handler.py python/ 
+          pip install -r requirements.txt -t python
+          cp set_candidate_rating_handler.py python/
           cd python
-          zip -r ../../../set-candidate-rating_handler_lambda.zip .
+          zip -r ../set-candidate-rating_handler_lambda.zip .
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+          aws-region: us-east-2
 
       - name: "Debug: Current directory and files"
         run: |
           echo "Current directory: $(pwd)"
-          ls -l
+          ls -l lambda/candidate_rating/set_candidate_rating
 
       - name: Verify set-candidate-rating_handler_lambda.zip exists
         run: |
-          if [ ! -f $(pwd)/set-candidate-rating_handler_lambda.zip ]; then echo "set-candidate-rating_handler_lambda.zip does not exist"; exit 1; fi
+          if [ ! -f lambda/candidate_rating/set_candidate_rating/set-candidate-rating_handler_lambda.zip ]; then echo "ZIP not found"; exit 1; fi
 
       - name: Deploy set-candidate-rating to AWS Lambda
         run: |
           aws lambda update-function-code \
             --function-name set_candidate_rating \
-            --zip-file fileb://$(pwd)/set-candidate-rating_handler_lambda.zip
+            --zip-file fileb://lambda/candidate_rating/set_candidate_rating/set-candidate-rating_handler_lambda.zip
